# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   usuario_dao:
        class: AppBundle\Model\Dao\UsuarioDao
        autowire: true